name: build-metadata
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: "17"
      distribution:
        type: string
        default: "temurin"

jobs:
  get-version:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: maven
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: get-version
    - name: Print Version
      env:
        VERSION: ${{ steps.get-version.outputs.version }}
      run: echo "version=${VERSION}"
    - name: Determine if Deploy
      id: determine-deploy
      # We want to build releases from tags matching the correct pattern and matching the pom version.
      # We want to build snapshot releases from any push to main.
      env:
        VERSION: ${{ steps.get-version.outputs.version }}
        REF: ${{ github.ref }}
      run: |
        if [ "refs/tags/v${VERSION}" = "${REF}" ] && [ "${VERSION}" ~= "[0-9]+.[0-9]+.[0-9]" ]; then
          echo "::set-output name=deploy::true"
          echo "::set-output name=release::true"
        elif [ "${REF}" = "refs/head/main" ] && [ "${VERSION}" ~=  "[0-9]+.[0-9]+.[0-9]-SNAPSHOT" ]; then
          echo "::set-output name=deploy::true"
          echo "::set-output name=release::false"
        else
          echo "::set-output name=deploy::false"
        fi
    - name: Print Deploy
      id: print-deploy
      env:
        DEPLOY: ${{ steps.determine-deploy.outputs.deploy }}
      run: echo "deploy=${DEPLOY}"

